In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np
from scipy import sparse
from glob import glob

In [2]:
fls = glob(r'data\processed\fifth_ring\supply\*.csv.gz')
for f in fls:
    print(f)

data\processed\fifth_ring\supply\driver_chains.csv.gz
data\processed\fifth_ring\supply\idle_windows.csv.gz
data\processed\fifth_ring\supply\supply_available_by_cluster.csv.gz
data\processed\fifth_ring\supply\supply_fleet_lower_bound.csv.gz
data\processed\fifth_ring\supply\supply_in_service_od.csv.gz
data\processed\fifth_ring\supply\trip_segments.csv.gz

In [3]:
for chunk in pd.read_csv(r'data\processed\fifth_ring\supply\driver_chains.csv.gz',chunksize=1000):
    break
chunk.head()

,chain_id,driver_id,date_,chain_seq,chain_start,chain_end,segment_count,segment_ids
0,562950053808583_2017-06-01_1,562950053808583,2017-06-01,1,2017-06-01 00:46:28,2017-06-01 01:25:04,2,"[""order_17593028586427"", ""order_17593028654751""]"
1,562950053808583_2017-06-01_2,562950053808583,2017-06-01,2,2017-06-01 10:34:45,2017-06-01 10:52:31,1,"[""order_17593034390450""]"
2,562950053808583_2017-06-01_3,562950053808583,2017-06-01,3,2017-06-01 19:46:13,2017-06-01 20:30:22,1,"[""order_17593045892007""]"
3,562950053809475_2017-06-01_1,562950053809475,2017-06-01,1,2017-06-01 08:20:15,2017-06-01 10:21:08,3,"[""carpool_562950053809475_1"", ""carpool_5629500..."
4,562950053855353_2017-06-01_1,562950053855353,2017-06-01,1,2017-06-01 07:02:29,2017-06-01 07:49:45,3,"[""order_17593030059974"", ""order_17593030274509..."

In [4]:
for chunk in pd.read_csv(r'data\processed\fifth_ring\supply\idle_windows.csv.gz',chunksize=1000):
    break
chunk.head()

,chain_id,driver_id,idle_start,idle_end,idle_cluster_id,idle_duration_s
0,562950053808583_2017-06-01_1,562950053808583,2017-06-01 01:00:11,2017-06-01 01:02:57,83,166.0
1,562950053809475_2017-06-01_1,562950053809475,2017-06-01 09:00:12,2017-06-01 09:18:12,96,1080.0
2,562950053809475_2017-06-01_1,562950053809475,2017-06-01 09:54:06,2017-06-01 10:03:15,96,549.0
3,562950053855353_2017-06-01_1,562950053855353,2017-06-01 07:14:29,2017-06-01 07:15:34,5,65.0
4,562950053855353_2017-06-01_1,562950053855353,2017-06-01 07:27:28,2017-06-01 07:40:38,5,790.0

In [9]:
for i, chunk in enumerate(pd.read_csv(r'data\processed\fifth_ring\supply\supply_available_by_cluster.csv.gz',chunksize=10000)):
    if i<=2:
        continue
    break
chunk.head()

                slot_start  cluster_id  available_vehicles
30000  2017-06-03 11:00:00           3                 102
30001  2017-06-03 11:00:00           4                   3
30002  2017-06-03 11:00:00           5                 110
30003  2017-06-03 11:00:00           6                  10
30004  2017-06-03 11:00:00           7                  47

In [6]:
for chunk in pd.read_csv(r'data\processed\fifth_ring\supply\supply_fleet_lower_bound.csv.gz',chunksize=1000):
    break
chunk.head()

,slot_start,cluster_id,fleet_lower_bound_cluster,global_fleet_lower_bound
0,2017-06-01 00:00:00,0,55,2766
1,2017-06-01 00:00:00,1,84,2766
2,2017-06-01 00:00:00,2,1,2766
3,2017-06-01 00:00:00,3,54,2766
4,2017-06-01 00:00:00,4,0,2766

In [ ]:
for chunk in pd.read_csv(r'data\processed\fifth_ring\supply\supply_in_service_od.csv.gz',chunksize=1000):
    if i<=2:
        continue
    break
chunk.head()

,slot_start,origin_cluster_id,destination_cluster_id,vehicles_in_service
0,2017-06-01 00:00:00,0,0,3
1,2017-06-01 00:00:00,0,7,1
2,2017-06-01 00:00:00,0,8,1
3,2017-06-01 00:00:00,0,12,1
4,2017-06-01 00:00:00,0,14,1

In [8]:
for chunk in pd.read_csv(r'data\processed\fifth_ring\supply\trip_segments.csv.gz',chunksize=1000):
    break
chunk.head()

,segment_id,driver_id,trip_start,trip_end,origin_cluster_id,destination_cluster_id,service_type,order_ids
0,order_17593028586427,562950053808583,2017-06-01 00:46:28,2017-06-01 01:00:11,75,83,exclusive,[17593028586427]
1,order_17593028654751,562950053808583,2017-06-01 01:02:57,2017-06-01 01:25:04,83,45,exclusive,[17593028654751]
2,order_17593034390450,562950053808583,2017-06-01 10:34:45,2017-06-01 10:52:31,75,83,exclusive,[17593034390450]
3,order_17593045892007,562950053808583,2017-06-01 19:46:13,2017-06-01 20:30:22,29,27,exclusive,[17593045892007]
4,carpool_562950053809475_1,562950053809475,2017-06-01 08:20:15,2017-06-01 09:00:12,46,96,carpool,"[17593031637413, 17593032068986]"