In [3]:
import geopandas as gpd
import pandas as pd
import numpy as np
from scipy import sparse

In [5]:
f = gpd.read_file('regularized_zoning_experiments/runs/v2_fifth_ring_road_poi_order_lc1_lr1_k100/clusters/segment_clusters_road_poi_order_regularized_leiden_lc1p0_lr1p0.gpkg')

In [6]:
f.head(100)

,u,v,key,osmid,name,highway,oneway,length,bridge,tunnel,...,lanes,maxspeed,junction,seg_id,segment_role,bearing,cluster_id,regularized_init,setting_id,geometry
0,25585055,533650673,0,8365687,人大会堂西路,tertiary,False,220.180409,NaN,NaN,...,NaN,NaN,NaN,seg_0000000,ordinary,163.167805,31,leiden,lc1p0_lr1p0,"LINESTRING (447479.253 4417060.259, 447486.159..."
1,25585055,8835880543,0,127844311,人大会堂西路,tertiary,False,435.772630,NaN,NaN,...,NaN,NaN,NaN,seg_0000001,ordinary,90.079505,31,leiden,lc1p0_lr1p0,"LINESTRING (447479.253 4417060.259, 447479.163..."
2,25585055,342791346,0,161809912,人大会堂西路,tertiary,False,67.033394,NaN,NaN,...,NaN,NaN,NaN,seg_0000002,ordinary,74.592492,31,leiden,lc1p0_lr1p0,"LINESTRING (447479.253 4417060.259, 447468.111..."
3,25585083,9378036221,0,1145602707,前门西大街,primary,True,105.203375,NaN,NaN,...,NaN,NaN,NaN,seg_0000004,ordinary,1.268827,31,leiden,lc1p0_lr1p0,"LINESTRING (447579.561 4416727.529, 447495.349..."
4,25585092,1414035092,0,4263918,兵部洼胡同,tertiary,False,14.287302,NaN,NaN,...,NaN,NaN,NaN,seg_0000005,ordinary,90.700606,31,leiden,lc1p0_lr1p0,"LINESTRING (447156.355 4416715.895, 447156.18 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,31194145,8559502659,0,229773673,朝阳门南小街,secondary,True,9.377709,NaN,NaN,...,NaN,NaN,NaN,seg_0000106,ordinary,99.653124,45,leiden,lc1p0_lr1p0,"LINESTRING (450460.325 4418398.348, 450461.898..."
96,31194147,384057956,0,25109457,东四南大街,primary,False,48.542161,NaN,NaN,...,NaN,NaN,NaN,seg_0000107,ordinary,92.215759,45,leiden,lc1p0_lr1p0,"LINESTRING (449698.926 4418756.313, 449700.802..."
97,31194147,9591211179,0,229775895,东四南大街,primary,False,593.672411,NaN,NaN,...,NaN,NaN,NaN,seg_0000108,ordinary,90.820791,22,leiden,lc1p0_lr1p0,"LINESTRING (449698.926 4418756.313, 449698.742..."
98,31194147,733859147,0,229775899,灯市口大街,tertiary,False,104.850034,NaN,NaN,...,NaN,NaN,NaN,seg_0000109,ordinary,2.949289,45,leiden,lc1p0_lr1p0,"LINESTRING (449698.926 4418756.313, 449685.587..."
99,31194226,31194236,0,169204611,首都机场高速公路,trunk,True,115.139637,NaN,NaN,...,3,NaN,NaN,seg_0000110,ordinary,48.974495,56,leiden,lc1p0_lr1p0,"LINESTRING (452836.095 4423019.276, 452875.567..."

In [12]:
d = pd.read_csv(r"data\raw\beijing_order_201710.csv",chunksize=10000)
for chunk in d:
    c = chunk.head()
    break

In [13]:
c

,order_id,driver_id,passenger_id,starting_lng,starting_lat,dest_lng,dest_lat,departure_time,finish_time,strive_time,current_lng,current_lat,total_fee,driver_start_distance,start_dest_distance,normal_distance,dvalue_time
0,17596204008362,564929892648709,3019379639407,116.154551,39.755012,116.136165,39.738352,2017-10-03 00:00:10,2017-10-03 00:15:14,2017-10-03 00:00:13,116.155260,39.754961,11.20,121,3679,3.2,15.0
1,17596204009519,564834156620281,1617196493975,116.420353,39.838352,116.377483,39.834007,2017-10-03 00:00:25,2017-10-03 00:11:04,2017-10-03 00:00:28,116.419305,39.838340,11.73,985,5198,4.9,10.0
2,17596204010587,564837185433271,5000118713832,116.396973,39.932135,116.439426,39.945655,2017-10-03 00:00:38,2017-10-03 00:19:44,2017-10-03 00:00:42,116.396841,39.932137,32.30,1495,6243,6.1,19.0
3,17596204019487,563563983863810,3465069069545,116.642080,39.892304,116.372784,39.863600,2017-10-03 00:02:27,2017-10-03 00:50:12,2017-10-03 00:02:30,116.640784,39.892991,82.27,292,29235,32.1,47.0
4,17596204022695,566151949389814,3190844621105,116.410087,39.949488,116.507521,39.928808,2017-10-03 00:03:05,2017-10-03 00:32:24,2017-10-03 00:03:14,116.409606,39.949116,36.25,603,13023,13.0,29.0

In [28]:
g = sparse.load_npz(r'data\processed\fifth_ring\order_pipeline\cluster_graph_road_adjacency_normalized.npz')

In [31]:
print(g.shape)
g

(100, 100)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 622 stored elements and shape (100, 100)>

In [4]:
order5 = pd.read_csv(r'data\raw\beijing_orders_2017-06_2017-08.csv.gz')
order5.to_csv(r'data\raw\beijing_orders_2017-06_2017-08.csv', index=False)

In [3]:
order5.head()

,departure_lon_wgs,departure_lat_wgs,arrival_lon_wgs,arrival_lat_wgs,departure_time,arrival_time
id,,,,,,
16045449,116.588482,40.078744,116.399677,40.036517,2017-06-02 13:23:00,2017-06-02 14:52:14
16048720,116.355188,39.957867,116.608934,40.053698,2017-06-01 03:30:00,2017-06-01 04:24:21
16049429,116.445778,39.903960,116.609414,40.054046,2017-06-01 08:00:00,2017-06-01 08:09:13
16050011,116.586611,40.078884,116.215947,39.955418,2017-06-01 10:01:00,2017-06-01 11:22:35
16050048,116.459793,39.870316,116.587604,40.079293,2017-06-01 09:20:00,2017-06-01 10:55:56

In [1]:
order5.to_csv(r'data\raw\beijing_order.csv', index=False)

NameError: name 'order5' is not defined